connection_throttle: 4000
online_mode: false
remote_ping_timeout: 5000
groups:
  md_5:
  - admin
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
remote_ping_cache: -1
connection_throttle_limit: 3
enforce_secure_profile: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 100
  tab_size: 60
  force_default_server: false
server_connect_timeout: 5000
player_limit: -1
max_packets_per_second: 4096
ip_forward: true
disabled_commands:
- disabledcommandhere
log_pings: true
max_packets_data_per_second: 33554432
forge_support: false
log_commands: false
stats: 462d1041-fbf4-4c3b-83c2-fc009849dccd
reject_transfers: false
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - bungeecord.command.send
  - bungeecord.command.find
prevent_proxy_connections: false
timeout: 30000
